name: CRD-RDP-Setup

on:
  workflow_dispatch:
    inputs:
      crd_token:
        description: 'Paste your CRD headless registration command here'
        required: true
        default: ''
      pin:
        description: '6-digit PIN for CRD'
        required: true
        default: '123456'

jobs:
  setup-crd:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Chrome silently (fixed)
        shell: powershell
        run: |
          Write-Output "Installing Chrome..."
          $chromePath = "C:\Program Files\Google\Chrome\Application\chrome.exe"
          if (-Not (Test-Path $chromePath)) {
              $chromeTempDir = "$env:TEMP\chrome_install"
              New-Item -ItemType Directory -Path $chromeTempDir -Force | Out-Null
              $chromeUrl = "https://dl.google.com/chrome/install/standalonesetup64.msi"
              $chromeMsi = "$chromeTempDir\chrome.msi"
              Invoke-WebRequest -Uri $chromeUrl -OutFile $chromeMsi -UseBasicParsing
              Start-Process msiexec -ArgumentList "/i `"$chromeMsi`" /quiet /norestart" -Wait
              Remove-Item -Recurse -Force $chromeTempDir
          } else {
              Write-Output "Chrome already installed, skipping..."
          }

      - name: Install CRD host & register headless
        shell: powershell
        run: |
          $HeadlessCommand = '${{ github.event.inputs.crd_token }}'
          $PIN = '${{ github.event.inputs.pin }}'
          Write-Output "Installing Chrome Remote Desktop host..."
          $TempDir = "$env:TEMP\crd_install"
          New-Item -ItemType Directory -Path $TempDir -Force | Out-Null
          
          # Correct CRD host download link
          $crdUrl = "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi"
          $crdMsi = "$TempDir\crd.msi"
          Invoke-WebRequest -Uri $crdUrl -OutFile $crdMsi -UseBasicParsing
          Start-Process msiexec -ArgumentList "/i `"$crdMsi`" /quiet /norestart" -Wait
          
          Write-Output "Registering host headlessly..."
          # Run the headless registration command provided via input box
          Invoke-Expression $HeadlessCommand
          Write-Output "CRD registration complete. Your machine should now appear in your devices list."

      - name: Cleanup
        shell: powershell
        run: |
          Remove-Item -Recurse -Force "$env:TEMP\crd_install"
